// <auto-generated />
namespace MovieSoft.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class dbIDcol : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbIDcol));
        
        string IMigrationMetadata.Id
        {
            get { return "201503121631584_db ID col"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
